#!/bin/sh

echo "Is it morning? Please answer 'yes' or 'no'"
read timeofday

case "$timeofday" in
	yes | y | Yes | YES ) echo "Good Morning!";;
	n | N* ) echo "Good Afternoon!";; #exemplo de uso de * em case, * serve como coringa
	* ) echo "Sorry, answer not recognised!";; 
esac 
exit 0
